// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTrYmtfTNe_fJr2kEpT_0QRcTwnrBJtps',
    appId: '1:28226275088:web:a1cd370fcde40ac881c795',
    messagingSenderId: '28226275088',
    projectId: 'mynotes-flutter-aminekoubaa',
    authDomain: 'mynotes-flutter-aminekoubaa.firebaseapp.com',
    storageBucket: 'mynotes-flutter-aminekoubaa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUMhYh4PxDmmP3ppTj46sC3XAL6Hv0cTE',
    appId: '1:28226275088:android:1f746fc9c03e86d781c795',
    messagingSenderId: '28226275088',
    projectId: 'mynotes-flutter-aminekoubaa',
    storageBucket: 'mynotes-flutter-aminekoubaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYBuDTVbgLyOGnxReOvwxA8F02k3b46PY',
    appId: '1:28226275088:ios:a8c79d774f4f21fc81c795',
    messagingSenderId: '28226275088',
    projectId: 'mynotes-flutter-aminekoubaa',
    storageBucket: 'mynotes-flutter-aminekoubaa.firebasestorage.app',
    iosBundleId: 'com.example.myprivatenotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYBuDTVbgLyOGnxReOvwxA8F02k3b46PY',
    appId: '1:28226275088:ios:a8c79d774f4f21fc81c795',
    messagingSenderId: '28226275088',
    projectId: 'mynotes-flutter-aminekoubaa',
    storageBucket: 'mynotes-flutter-aminekoubaa.firebasestorage.app',
    iosBundleId: 'com.example.myprivatenotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTrYmtfTNe_fJr2kEpT_0QRcTwnrBJtps',
    appId: '1:28226275088:web:7f94195ea12a157a81c795',
    messagingSenderId: '28226275088',
    projectId: 'mynotes-flutter-aminekoubaa',
    authDomain: 'mynotes-flutter-aminekoubaa.firebaseapp.com',
    storageBucket: 'mynotes-flutter-aminekoubaa.firebasestorage.app',
  );

}